/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.4.0

Source Server         : 10.248.24.159
Source Server Version : 110200
Source Host           : 10.248.24.159:1521
Source Schema         : YBOLTP

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2017-08-10 14:01:00
*/


-- ----------------------------
-- Table structure for TB_TJRSTJ
-- ----------------------------
DROP TABLE "YBOLTP"."TB_TJRSTJ";
CREATE TABLE "YBOLTP"."TB_TJRSTJ" (
"YYDM" CHAR(16 BYTE) NOT NULL ,
"TJLX" CHAR(2 BYTE) NOT NULL ,
"TJRQ" CHAR(8 BYTE) NOT NULL ,
"KYYRS" NUMBER(4) NULL ,
"YYRS" NUMBER(4) NULL ,
"XSKYYRS" NUMBER(4) DEFAULT 0  NOT NULL ,
"XSYYRS" NUMBER(4) DEFAULT 0  NOT NULL 
)
NOLOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of TB_TJRSTJ
-- ----------------------------
INSERT INTO "YBOLTP"."TB_TJRSTJ" VALUES ('125200          ', '01', '20170630', '2341', '39', '0', '0');

-- ----------------------------
-- Table structure for TB_TJRSTJ_LOG
-- ----------------------------
DROP TABLE "YBOLTP"."TB_TJRSTJ_LOG";
CREATE TABLE "YBOLTP"."TB_TJRSTJ_LOG" (
"LSH" CHAR(20 BYTE) NOT NULL ,
"YYDM" CHAR(16 BYTE) NOT NULL ,
"TJLX" CHAR(2 BYTE) NOT NULL ,
"TJRQ" CHAR(8 BYTE) NOT NULL ,
"KYYRS" NUMBER(4) NULL ,
"YYRS" NUMBER(4) NULL ,
"CZR" VARCHAR2(100 BYTE) NULL ,
"CZSJ" DATE NULL ,
"XSKYYRS" NUMBER(4) DEFAULT 0  NOT NULL ,
"XSYYRS" NUMBER(4) DEFAULT 0  NOT NULL 
)
NOLOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of TB_TJRSTJ_LOG
-- ----------------------------

-- ----------------------------
-- Table structure for TB_TJRYXX
-- ----------------------------
DROP TABLE "YBOLTP"."TB_TJRYXX";
CREATE TABLE "YBOLTP"."TB_TJRYXX" (
"TJDJH" CHAR(20 BYTE) NOT NULL ,
"TJND" CHAR(4 BYTE) NOT NULL ,
"TJLX" CHAR(2 BYTE) NULL ,
"SBKH" CHAR(9 BYTE) NOT NULL ,
"YBH" CHAR(8 BYTE) NOT NULL ,
"XM" VARCHAR2(100 BYTE) NULL ,
"SFZH" CHAR(18 BYTE) NULL ,
"XB" CHAR(1 BYTE) NULL ,
"NL" NUMBER(3) NULL ,
"RYLB" CHAR(2 BYTE) NULL ,
"RYZLB" CHAR(4 BYTE) NULL ,
"RYXSLB" CHAR(3 BYTE) NULL ,
"TJDC" CHAR(2 BYTE) NULL ,
"DWYBH" CHAR(8 BYTE) NULL ,
"YYDM" CHAR(16 BYTE) NULL ,
"TCBH" CHAR(4 BYTE) NULL ,
"TCBZ" NUMBER(9,2) NULL ,
"CBJE" NUMBER(9,2) NULL ,
"YYSJ" DATE NULL ,
"TJSJ" DATE NULL ,
"YYFS" CHAR(2 BYTE) NULL ,
"ZT" CHAR(2 BYTE) NULL ,
"HYZK" CHAR(1 BYTE) NULL ,
"BJXX" VARCHAR2(1000 BYTE) NULL 
)
NOLOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "YBOLTP"."TB_TJRYXX" IS '记录从体检人员名单生成->预约->上门体检->体检完成全过程';
COMMENT ON COLUMN "YBOLTP"."TB_TJRYXX"."TJLX" IS '字典：TB_DIC_TJLX ';
COMMENT ON COLUMN "YBOLTP"."TB_TJRYXX"."YYFS" IS '字典：TB_DIC_TJ_YYFS';
COMMENT ON COLUMN "YBOLTP"."TB_TJRYXX"."ZT" IS '00：初始状态（名单生成）
01：已预约
02：已上门体检
03：已出体检结果
04：预约撤销
';

-- ----------------------------
-- Records of TB_TJRYXX
-- ----------------------------
INSERT INTO "YBOLTP"."TB_TJRYXX" VALUES ('TJDJ2017060677888899', '2017', '01', 'A01534082', '10003676', '孙达军', '330203196412051511', '1', '52', '07', '0000', '100', '03', '10000007', '700063          ', '0007', '688', '203', TO_DATE('2017-06-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), null, '02', '00', '1', null);

-- ----------------------------
-- Indexes structure for table TB_TJRSTJ
-- ----------------------------

-- ----------------------------
-- Checks structure for table TB_TJRSTJ
-- ----------------------------
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("YYDM" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("TJLX" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("TJRQ" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("XSKYYRS" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("XSYYRS" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("YYDM" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("TJLX" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("TJRQ" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("XSKYYRS" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("XSYYRS" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("YYDM" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("TJLX" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("TJRQ" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("YYDM" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("TJLX" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("TJRQ" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("XSKYYRS" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD CHECK ("XSYYRS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TB_TJRSTJ
-- ----------------------------
ALTER TABLE "YBOLTP"."TB_TJRSTJ" ADD PRIMARY KEY ("YYDM", "TJLX", "TJRQ");

-- ----------------------------
-- Indexes structure for table TB_TJRSTJ_LOG
-- ----------------------------

-- ----------------------------
-- Checks structure for table TB_TJRSTJ_LOG
-- ----------------------------
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("LSH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("YYDM" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("TJLX" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("TJRQ" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("XSKYYRS" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("XSYYRS" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("LSH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("YYDM" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("TJLX" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("TJRQ" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("XSKYYRS" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("XSYYRS" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("LSH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("YYDM" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("TJLX" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("TJRQ" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("XSKYYRS" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD CHECK ("XSYYRS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TB_TJRSTJ_LOG
-- ----------------------------
ALTER TABLE "YBOLTP"."TB_TJRSTJ_LOG" ADD PRIMARY KEY ("LSH");

-- ----------------------------
-- Indexes structure for table TB_TJRYXX
-- ----------------------------

-- ----------------------------
-- Checks structure for table TB_TJRYXX
-- ----------------------------
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("TJDJH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("TJND" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("SBKH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("YBH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("TJDJH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("TJND" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("SBKH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("YBH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("TJDJH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("TJND" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("SBKH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("YBH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("TJDJH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("TJND" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("SBKH" IS NOT NULL);
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD CHECK ("YBH" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TB_TJRYXX
-- ----------------------------
ALTER TABLE "YBOLTP"."TB_TJRYXX" ADD PRIMARY KEY ("TJDJH");
